# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Producto.create!(nombre: 'Codigo de prueba', titular: 'Prueba de producto codigo', descripcion: 'Esto es un producto de prueba, vendiendo codigos de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'codigo')
Codigo.create!(codigo: '01234', vendido: true, producto_id: 1, pedido_id: 1)
Codigo.create!(codigo: '01235', vendido: false, producto_id: 1)
Codigo.create!(codigo: '01236', vendido: false, producto_id: 1)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Prueba', numero: 1, cp: 28021, provincia: 'Madrid', localidad: 'Madrid', cif: '123456-D', numeroFactura: 0001, pedido_id: 1, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:1, nombre: "Usuario de prueba", calle: "Calle de prueba", numero: "2", cp: "28023", localidad: "Madrid", provincia: "Madrid", cantidad: 1, producto_id: 1)

Producto.create!(nombre: 'Entrada de prueba', titular: 'Prueba de producto entrada', descripcion: 'Esto es un producto de prueba, vendiendo entradas de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'entrada')
Entrada.create!(codigo: '01234', vendido: true, producto_id: 2, pedido_id: 2)
Entrada.create!(codigo: '01235', vendido: false, producto_id: 2)
Entrada.create!(codigo: '01236', vendido: false, producto_id: 2)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Prueba', numero: 1, cp: 28021, provincia: 'Madrid', localidad: 'Madrid', cif: '123456-D', numeroFactura: 0002, pedido_id: 2, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:2, nombre: "Usuario de prueba", calle: "Calle de prueba", numero: "2", cp: "28023", localidad: "Madrid", provincia: "Madrid", cantidad: 1, producto_id: 2)

Producto.create!(nombre: 'Codigo de prueba 2', titular: 'Prueba de producto codigo 2', descripcion: 'Esto es un producto de prueba, vendiendo más codigos de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'codigo')
Codigo.create!(codigo: '01534', vendido: false, producto_id: 3, pedido_id: 3)
Codigo.create!(codigo: '01635', vendido: false, producto_id: 3)
Codigo.create!(codigo: '08236', vendido: true, producto_id: 3)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Lechuga', numero: 28, cp: 28941, provincia: 'Fuenlabrada', localidad: 'Madrid', cif: '124456-A', numeroFactura: 0003, pedido_id: 3, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:3, nombre: "Usuario de prueba", calle: "Calle de la Lechuga", numero: "28", cp: "28941", localidad: "Fuenlabrada", provincia: "Madrid", cantidad: 1, producto_id: 3)

Producto.create!(nombre: 'Entrada de prueba 2', titular: 'Prueba de producto entrada 2', descripcion: 'Esto es un producto de prueba, vendiendo más entradas de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'entrada')
Entrada.create!(codigo: '02341', vendido: true, producto_id: 4, pedido_id: 4)
Entrada.create!(codigo: '02351', vendido: false, producto_id: 4)
Entrada.create!(codigo: '02361', vendido: false, producto_id: 4)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Tomate', numero: 15, cp: 28900, provincia: 'Getafe', localidad: 'Madrid', cif: '123467-W', numeroFactura: 0004, pedido_id: 4, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:4, nombre: "Usuario de prueba", calle: "Calle del Tomate", numero: "15", cp: "28900", localidad: "Getafe", provincia: "Madrid", cantidad: 1, producto_id: 4)

Producto.create!(nombre: 'Codigo de prueba 3', titular: 'Prueba de producto codigo 3', descripcion: 'Esto es otro producto de prueba, vendiendo más codigos de prueba', precio: 10, estado: 'activo', stock: 4, tipoProducto: 'codigo')
Codigo.create!(codigo: '11036', vendido: false, producto_id: 5, pedido_id: 5)
Codigo.create!(codigo: '06385', vendido: false, producto_id: 5)
Codigo.create!(codigo: '01666', vendido: false, producto_id: 5)
Codigo.create!(codigo: '10284', vendido: false, producto_id: 5)
Codigo.create!(codigo: '08448', vendido: true, producto_id: 5)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Málaga', numero: 8, cp: 28290, provincia: 'Las Rozas', localidad: 'Madrid', cif: '169836-C', numeroFactura: 0005, pedido_id: 5, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:5, nombre: "Usuario de prueba", calle: "Calle de Málaga", numero: "8", cp: "28290", localidad: "Las Rozas", provincia: "Madrid", cantidad: 1, producto_id: 5)

Producto.create!(nombre: 'Entrada de prueba 3', titular: 'Prueba de producto entrada 3', descripcion: 'Esto es otro producto de prueba, vendiendo más entradas de prueba', precio: 10, estado: 'activo', stock: 4, tipoProducto: 'entrada')
Entrada.create!(codigo: '05431', vendido: true, producto_id: 6, pedido_id: 6)
Entrada.create!(codigo: '13489', vendido: false, producto_id: 6)
Entrada.create!(codigo: '10370', vendido: true, producto_id: 6)
Entrada.create!(codigo: '00036', vendido: false, producto_id: 6)
Entrada.create!(codigo: '12480', vendido: false, producto_id: 6)
Entrada.create!(codigo: '01749', vendido: false, producto_id: 6)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Bonito', numero: 12, cp: 28911, provincia: 'Leganés', localidad: 'Madrid', cif: '957339-H', numeroFactura: 0006, pedido_id: 6, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:6, nombre: "Usuario de prueba", calle: "Calle del Bonito", numero: "12", cp: "28911", localidad: "Leganés", provincia: "Madrid", cantidad: 1, producto_id: 6)

Producto.create!(nombre: 'Codigo de prueba 4', titular: 'Prueba de producto codigo 4', descripcion: 'Esto es otro producto más de prueba, vendiendo aún más codigos de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'codigo')
Codigo.create!(codigo: '11136', vendido: false, producto_id: 7, pedido_id: 7)
Codigo.create!(codigo: '06395', vendido: false, producto_id: 7)
Codigo.create!(codigo: '01606', vendido: false, producto_id: 7)
Codigo.create!(codigo: '10286', vendido: false, producto_id: 7)
Codigo.create!(codigo: '08458', vendido: true, producto_id: 7)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Grillo', numero: 1, cp: 28290, provincia: 'Las Rozas', localidad: 'Madrid', cif: '169845-B', numeroFactura: 0007, pedido_id: 7, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:7, nombre: "Usuario de prueba", calle: "Calle del Grillo", numero: "1", cp: "28291", localidad: "Las Rozas", provincia: "Madrid", cantidad: 1, producto_id: 7)

Producto.create!(nombre: 'Entrada de prueba 4', titular: 'Prueba de producto entrada 4', descripcion: 'Esto es otro producto más de prueba, vendiendo aún más entradas de prueba', precio: 10, estado: 'activo', stock: 3, tipoProducto: 'entrada')
Entrada.create!(codigo: '05431', vendido: true, producto_id: 8, pedido_id: 8)
Entrada.create!(codigo: '13489', vendido: false, producto_id: 8)
Entrada.create!(codigo: '10370', vendido: true, producto_id: 8)
Entrada.create!(codigo: '12480', vendido: false, producto_id: 8)
Entrada.create!(codigo: '01749', vendido: false, producto_id: 8)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Granada', numero: 24, cp: 28912, provincia: 'Leganés', localidad: 'Madrid', cif: '196845-X', numeroFactura: 8, pedido_id: 8, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:8, nombre: "Usuario de prueba", calle: "Calle de Granada", numero: "24", cp: "28912", localidad: "Leganés", provincia: "Madrid", cantidad: 1, producto_id: 8)

Producto.create!(nombre: 'Codigo de prueba 5', titular: 'Prueba de producto codigo 5', descripcion: 'Esto es otro producto más de prueba, vendiendo aún más codigos de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'codigo')
Codigo.create!(codigo: '17927', vendido: false, producto_id: 9, pedido_id: 9)
Codigo.create!(codigo: '17090', vendido: false, producto_id: 9)
Codigo.create!(codigo: '17394', vendido: false, producto_id: 9)
Codigo.create!(codigo: '17294', vendido: false, producto_id: 9)
Codigo.create!(codigo: '17273', vendido: true, producto_id: 9)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Somormujo', numero: 19, cp: 28923, provincia: 'Alcorcón', localidad: 'Madrid', cif: '168845-K', numeroFactura: 9, pedido_id: 9, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:9, nombre: "Usuario de prueba", calle: "Calle de Somormujo", numero: "19", cp: "28923", localidad: "Alcorcón", provincia: "Madrid", cantidad: 1, producto_id: 9)

Producto.create!(nombre: 'Entrada de prueba 5', titular: 'Prueba de producto entrada 5', descripcion: 'Esto es otro producto más de prueba, vendiendo aún más entradas de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'entrada')
Entrada.create!(codigo: '98679', vendido: true, producto_id: 10, pedido_id: 10)
Entrada.create!(codigo: '98649', vendido: true, producto_id: 10)
Entrada.create!(codigo: '98678', vendido: true, producto_id: 10)
Entrada.create!(codigo: '98524', vendido: false, producto_id: 10)
Entrada.create!(codigo: '98625', vendido: false, producto_id: 10)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Filipinas', numero: 4, cp: 28920, provincia: 'Alcorcón', localidad: 'Madrid', cif: '177845-J', numeroFactura: 0010, pedido_id: 10, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:10, nombre: "Usuario de prueba", calle: "Calle de Filipinas", numero: "4", cp: "28920", localidad: "Alcorcón", provincia: "Madrid", cantidad: 1, producto_id: 10)

Producto.create!(nombre: 'Codigo de prueba 6', titular: 'Prueba de producto codigo 6', descripcion: 'Esto es el último producto de prueba, vendiendo más codigos de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'codigo')
Codigo.create!(codigo: '17527', vendido: false, producto_id: 11, pedido_id: 11)
Codigo.create!(codigo: '17590', vendido: false, producto_id: 11)
Codigo.create!(codigo: '17594', vendido: false, producto_id: 11)
Codigo.create!(codigo: '17592', vendido: false, producto_id: 11)
Codigo.create!(codigo: '17573', vendido: true, producto_id: 11)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Alcalá', numero: 19, cp: 28001, provincia: 'Madrid', localidad: 'Madrid', cif: '169975-L', numeroFactura: 0011, pedido_id: 11, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:11, nombre: "Usuario de prueba", calle: "Calle de Alcalá", numero: "19", cp: "28923", localidad: "Madrid", provincia: "Madrid", cantidad: 1, producto_id: 11)

Producto.create!(nombre: 'Entrada de prueba 6', titular: 'Prueba de producto entrada 6', descripcion: 'Esto es el último producto de prueba, vendiendo más entradas de prueba', precio: 10, estado: 'activo', stock: 2, tipoProducto: 'entrada')
Entrada.create!(codigo: '92679', vendido: true, producto_id: 12, pedido_id: 12)
Entrada.create!(codigo: '92649', vendido: true, producto_id: 12)
Entrada.create!(codigo: '92678', vendido: true, producto_id: 12)
Entrada.create!(codigo: '92524', vendido: false, producto_id: 12)
Entrada.create!(codigo: '92625', vendido: false, producto_id: 12)
Factura.create!(nombre: 'Usuario Prueba', calle: 'C/Solas', numero: 42, cp: 45070, provincia: 'Toledo', localidad: 'Castilla-La Mancha', cif: '177845-J', numeroFactura: 0012, pedido_id: 12, importe: 10)
Pedido.create!(mail: 'ejemplo@ejemplo.com', precio: 10, factura_id:12, nombre: "Usuario de prueba", calle: "Calle de Solas", numero: "42ra", cp: "45070", localidad: "Toledo", provincia: "Castilla-La Mancha", cantidad: 1, producto_id: 12)
